select * from customer
--Q1. what is the total revenue generated by male vs female?
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender
Order by total_revenue desc

 --Q2. which customer used a discount but still spent more than the average purchase amount?
 select customer_id ,  purchase_amount
 from customer 
 where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer )

--Q3. which are the top 5 products with highest average review rating 
select item_purchased,
ROUND (avg(review_rating::numeric),2)  as average_review_rating
from customer
group by  item_purchased
order by average_review_rating
limit 5

-- Q4. Compare the average Purchase Amounts between standard and express shipping 
select shipping_type , round(avg(purchase_amount),2) as average_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type 

--Q5. Do subsriber spend more? compare average spend and total spend revenue
select subscription_status,
count(customer_id) as total_number,
round(avg(purchase_amount),2) as average_spend,
sum(purchase_amount) as total_spend
from customer
group by subscription_status
order by average_spend, total_spend;

--Q6. which 5 products have the most percentage of the purchase with discount

select item_purchased,
100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. segment customers into new, returning and loyal based on their total
--number of previous purchase and show the count of each segment
with customer_type as (
  select customer_id, previous_purchases,
  case 
  when previous_purchases=1 then 'New'
  when previous_purchases between 2 and 10 then 'Returning'
  else 'Loyal'
  end as customer_segment
from customer
)
select customer_segment , count(*) as "Number of Customer"
from customer_type 
group by customer_segment

--Q8. what are the top 3 most purchases products within each category?
with item_counts as (
select category , item_purchased, 
count (customer_id) as total_orders,
row_number() over(partition by category order by count (customer_id) desc )as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count (customer_id) as repeat_buyers
from customer
where previous_purchases >5 
group by subscription_status

--Q10. What is the revenue contribution of each age group?
with revenue_contribution as(
select age_group, 
sum(purchase_amount) as total_revenue
from customer
group by age_group
)
select age_group,total_revenue ,
ROUND(100 * total_revenue / SUM(total_revenue) over() ,2)as percentage_of_contribution
from revenue_contribution
group by age_group, total_revenue
order by total_revenue desc;






 



